import { Inter , Oxanium} from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer/page";
import LayoutWrapper from "../components/LayoutWrapper/LayoutWrapper";

const inter = Inter({ subsets: ["latin"] });
const oxanium = Oxanium({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oxanium.className}>
        <div style={{position:"relative"}}>
          <LayoutWrapper>
          {children}
            </LayoutWrapper>
          
          <Footer/>
        </div>
        </body>
    </html>
  );
}
